export const UPDATE_STOCK_DATA = 'UPDATE_STOCK_DATA';
export const FIND_COMPANIES = 'FIND_COMPANIES';
export const CLEAR_STOCKS = 'CLEAR_STOCKS';
export const CLEAR_COMPANIES = 'CLEAR_COMPANIES';
export const PREDICT_PRICES = 'PREDICT_PRICES';
export const CLEAR_PRICES = 'CLEAR_PRICES';
