export const UPDATE_STOCK_DATA = 'UPDATE_STOCK_DATA';
export const FIND_COMPANIES = 'FIND_COMPANIES';

export const CLEAR_STOCKS = 'CLEAR_STOCKS';
export const CLEAR_COMPANIES = 'CLEAR_COMPANIES';

export const PREDICT_PRICES = 'PREDICT_PRICES';
export const CLEAR_PRICES = 'CLEAR_PRICES';

export const UPDATE_TWITTER_RESULTS = 'UPDATE_TWITTER_RESULTS'
export const CLEAR_TWITTER_RESULTS = 'CLEAR_TWITTER_RESULTS'

export const UPDATE_COMPANY_NEWS = 'UPDATE_COMPANY_NEWS'
export const CLEAR_COMPANY_NEWS = 'CLEAR_COMPANY_NEWS'
